SRC=refcard.tex

all: $(SRC:.tex=.pdf) preview.png

%.pdf: %.tex | revision.tex
	latexmk $<

revision.tex:
	git config --global --add safe.directory /srv
	echo "% Autogenerated, do not edit" > $@
	echo "\\\\newcommand{\\\\revisiondate}{`git log -1 --format=\"%ad\" --date=short`}" >> $@
	echo "\\\\newcommand{\\\\revision}{`git describe`}" >> $@

underlay.pdf: underlay.tex
	latexmk $<

preview.pdf: $(SRC)
	latexmk -jobname=$(basename $@) -pdflatex='lualatex %O "\def\tinted{tinted}\input{%S}"' $<

%.png: %.pdf
	gs -dSAFER -r150 -sDEVICE=png16m -dLastPage=1 -o $@ $<

clean:
	latexmk -C
	$(RM) *.log *.fls *.aux *.fdb_latexmk *.pdf *.xdv revision.tex $(SRC:.tex=.pdf)

.PHONY: clean
