all: refcard.tex revision.tex
	latexmk -pdf -xelatex $<

revision.tex:
	echo "% Autogenerated, do not edit" > $@
	echo "\\\\newcommand{\\\\revisiondate}{`git log -1 --format=\"%ad\" --date=short`}" >> $@
	echo "\\\\newcommand{\\\\revision}{`git describe`}" >> $@

clean:
	latexmk -C

.PHONY: clean